name: awesome-go-sql

services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: awesome
    volumes:
      - ./data:/docker-entrypoint-initdb.d:ro
